# Generated by Django 5.0.6 on 2024-06-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='url',
            new_name='part_url',
        ),
    ]
