# Generated by Django 5.0.6 on 2024-06-12 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_url_request_part_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.bcruser'),
        ),
        migrations.RemoveField(
            model_name='operations',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.bcruser'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='bcruser',
            name='type',
            field=models.TextField(choices=[('Student', 'Student'), ('Mentor', 'Mentor'), ('Operations', 'Operations')], default='Student'),
        ),
        migrations.AlterField(
            model_name='request',
            name='supplier',
            field=models.TextField(choices=[('Test Supplier 1', 'Test Supplier 1'), ('Test Supplier 2', 'Test Supplier 2'), ('Test Supplier 3', 'Test Supplier 3')]),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Operations',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
