# Generated by Django 5.0.6 on 2024-06-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_mentor_user_alter_review_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='submitter',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
